# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import messages_pb2 as messages__pb2


class AnomalyDetectionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamData = channel.stream_stream(
                '/AnomalyDetectionService/StreamData',
                request_serializer=messages__pb2.NumpyArray.SerializeToString,
                response_deserializer=messages__pb2.AnomalyDetResponse.FromString,
                )


class AnomalyDetectionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamData(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnomalyDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamData': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamData,
                    request_deserializer=messages__pb2.NumpyArray.FromString,
                    response_serializer=messages__pb2.AnomalyDetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AnomalyDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AnomalyDetectionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/AnomalyDetectionService/StreamData',
            messages__pb2.NumpyArray.SerializeToString,
            messages__pb2.AnomalyDetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
