# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"D\n\nNumpyArray\x12\x0e\n\x06values\x18\x01 \x03(\x01\x12\x0c\n\x04rows\x18\x02 \x01(\x05\x12\x0c\n\x04\x63ols\x18\x03 \x01(\x05\x12\n\n\x02id\x18\x04 \x01(\x05\"\x07\n\x05\x45mpty28\n\x11\x44\x61taBrokerService\x12#\n\ndatabroker\x12\x06.Empty\x1a\x0b.NumpyArray0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NUMPYARRAY']._serialized_start=18
  _globals['_NUMPYARRAY']._serialized_end=86
  _globals['_EMPTY']._serialized_start=88
  _globals['_EMPTY']._serialized_end=95
  _globals['_DATABROKERSERVICE']._serialized_start=97
  _globals['_DATABROKERSERVICE']._serialized_end=153
# @@protoc_insertion_point(module_scope)
